#pragma once

#include <SDL2/SDL.h>

#define NB_KEY_W SDL_SCANCODE_W
#define NB_KEY_A SDL_SCANCODE_A
#define NB_KEY_S SDL_SCANCODE_S
#define NB_KEY_D SDL_SCANCODE_D

#define NB_KEY_SPACE SDL_SCANCODE_SPACE
#define NB_KEY_ESCAPE SDL_SCANCODE_ESCAPE

#define NB_KEY_UP SDL_SCANCODE_UP
#define NB_KEY_DOWN SDL_SCANCODE_DOWN
#define NB_KEY_LEFT SDL_SCANCODE_LEFT
#define NB_KEY_RIGHT SDL_SCANCODE_RIGHT
